apiVersion: v1
kind: Pod
metadata:
  name: book-service
spec:
  containers:
  - name: bookservice
    image: apptrustswampupb.jfrog.io/napa-burger-docker-local/book-service:15
    imagePullPolicy: Always
  imagePullSecrets: 
  - name: jfrog-secret