apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu
    image: z0apptrustdev.jfrogdev.org/barber-shop-docker-trial/ubuntu-with-tools:24.04
    imagePullPolicy: Always
  imagePullSecrets: 
  - name: jfrog-secret