apiVersion: constraints.gatekeeper.sh/v1beta1
kind: jfrogcheckevidence
metadata:
  name: jfrog-check-evidence
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    checkedRegistries: ["evidencetrial.jfrog.io"]
    checkedPredicateTypes: ["https://slsa.dev/provenance/v1"]